default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: happytribe_development

test:
  <<: *default
  database: happytribe_test

production:
  <<: *default
  database: happytribe
